### ISSUE TITLE
ProfilerWorkloadListener : Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by talenyc** [spaghettidba/WorkloadTools#18]
Ever since Null or Not null release in I am getting following error :

Info - SqlWorkload.Program : SqlWorkload, Version=1.0.6.0, Culture=neutral, PublicKeyToken=null 1.0.6
Info - SqlWorkload.Program : Reading configuration from 'C:\Release\WorkloadTools\SqlWorkload.json'Info - WorkloadTools.Listener.Trace.TraceServerWrapper : SMO Version: Microsoft.SqlServer.ConnectionInfoExtended, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
Error - WorkloadTools.Listener.Trace.ProfilerWorkloadListener : Exception has been thrown by the target of an invocation.
Error - WorkloadTools.Listener.Trace.ProfilerWorkloadListener : Failed to initialize object as reader.
Error - WorkloadTools.WorkloadController : Uncaught Exception
Error - WorkloadTools.WorkloadController :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at WorkloadTools.Listener.Trace.TraceServerWrapper.InitializeAsReader(SqlConnectionInfoWrapper connectionInfo, String TraceDefinition)
in C:\progetti\WorkloadTools\WorkloadTools\Listener\Trace\TraceServerWrapper.cs:line 94
   at WorkloadTools.Listener.Trace.ProfilerWorkloadListener.Initialize() in C:\progetti\WorkloadTools\WorkloadTools\Listener\Trace\ProfilerWorkloadListener.cs:line 62
   at WorkloadTools.WorkloadController.Run() in C:\progetti\WorkloadTools\WorkloadTools\WorkloadController.cs:line 34
Info - SqlWorkload.Program : Controller stopped.

**Comment by spaghettidba** [comment]
Looks like you installed the x64 version over the x86 version. The profiler listener will not work in the x64 release. Sorry, there's nothing I can do about it, it's a limitation imposed but the profiler DLLs.
Moreover, the profiler listener has a non negligible performance overhead. I would recommend Extended Events or SqlTrace instead.
