### ISSUE TITLE
Cannot use ConvertWorkload tool

### ISSUE THREAD

**Issue by noamo48** [spaghettidba/WorkloadTools#57]
I am trying to use ConvertWorkload.exe to convert trace files captured with Database Experimentation Assistant. However, I keep getting these errors any time I try to run the command. I have tried from two different servers and the result is the same. 

PS C:\Program Files\WorkloadTools> .\ConvertWorkload.exe -i E:\CAPTURE\Minimum_ProdVMCapture_20190730111.trc -O E:\OUTPuT
Info - ConvertWorkload.Program : ConvertWorkload, Version=1.3.3.0, Culture=neutral, PublicKeyToken=null 1.3.3
Info - WorkloadTools.Listener.Trace.TraceFileWrapper : SMO Version: Microsoft.SqlServer.ConnectionInfoExtended, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
Error - ConvertWorkload.SqlTraceEventReader : Exception has been thrown by the target of an invocation.
Error - ConvertWorkload.SqlTraceEventReader : Failed to initialize object as reader.
Info - ConvertWorkload.Program : Received shutdown signal...
Info - WorkloadTools.Consumer.WorkloadFile.WorkloadFileWriterConsumer : Closing the connection to the output file
Error - ConvertWorkload.Program : System.UnhandledExceptionEventArgs
Caught unhandled exception...

Unhandled Exception: System.ArgumentException: Invalid ConnectionString format, cannot parse: string value to split cannot be null
   at System.Data.SQLite.SQLiteConnection.ParseConnectionString(SQLiteConnection connection, String connectionString, Boolean allowNameOnly)
   at System.Data.SQLite.SQLiteConnection.ParseConnectionString(SQLiteConnection connection, String connectionString, Boolean parseViaFramework, Boolean allowNameOnly)
   at System.Data.SQLite.SQLiteConnection.Open()
   at WorkloadTools.Consumer.WorkloadFile.WorkloadFileWriterConsumer.InitializeConnection() in C:\GitHub\WorkloadTools\WorkloadTools\Consumer\WorkloadFile\WorkloadFileWriterConsumer.cs:line 165
   at WorkloadTools.Consumer.WorkloadFile.WorkloadFileWriterConsumer.Flush() in C:\GitHub\WorkloadTools\WorkloadTools\Consumer\WorkloadFile\WorkloadFileWriterConsumer.cs:line 128
   at WorkloadTools.Consumer.WorkloadFile.WorkloadFileWriterConsumer.Dispose(Boolean disposing) in C:\GitHub\WorkloadTools\WorkloadTools\Consumer\WorkloadFile\WorkloadFileWriterConsumer.cs:line 404
   at WorkloadTools.Consumer.WorkloadConsumer.Dispose() in C:\GitHub\WorkloadTools\WorkloadTools\Consumer\WorkloadConsumer.cs:line 14
   at ConvertWorkload.WorkloadFileEventWriter.Dispose(Boolean disposing)
   at ConvertWorkload.EventWriter.Dispose()
   at ConvertWorkload.WorkloadConverter.Stop()
   at ConvertWorkload.Program.<>c__DisplayClass3_0.<Run>b__0(Object sender, ConsoleCancelEventArgs e)
   at System.Console.ControlCDelegate(Object data)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by spaghettidba** [comment]
It seems like you specified a folder instead of a file as the output for the conversion. You should specify a file name instead, like e:\output\Minimum_ProdVMCapture_20190730111.sqlite
